export {RegistryButton} from './RegistryButton'
export {AuthButton} from './AuthButton'
export {LoginInput} from './LoginInput'
export {PasswordInput} from './PasswordInput'
export {RepeatPasswordInput} from './RepeatPasswordInput'
export {SurnameInput} from './SurnameInput'
export {NameInput} from './NameInput'
export {EmailInput} from './EmailInput'